# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data

class AutoAvailableStatus(object):
    Enabled = 0
    NoHydraulicConnection = 1
    NoBusConnection = 2
    NoCameraConnection = 3

