# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data

class AutoEnabledStatus(object):
    Enabled = 0
    SteeringWheel = 1
    EndOrNoTrajectory = 2
    BadVisibility = 3

