# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data

class Data(object):
    NONE = 0
    Gps = 1
    View = 2
    TabView = 3
    Mustache = 4
    AutoStatus = 5
    CommonInfo = 6
    FWRegulator = 7
    Warning = 8


def DataCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == Data().Gps:
        import agroproto.data.Gps
        return agroproto.data.Gps.GpsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().View:
        import agroproto.data.View
        return agroproto.data.View.ViewT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().TabView:
        import agroproto.data.TabView
        return agroproto.data.TabView.TabViewT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().Mustache:
        import agroproto.data.Mustache
        return agroproto.data.Mustache.MustacheT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().AutoStatus:
        import agroproto.data.AutoStatus
        return agroproto.data.AutoStatus.AutoStatusT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().CommonInfo:
        import agroproto.data.CommonInfo
        return agroproto.data.CommonInfo.CommonInfoT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().FWRegulator:
        import agroproto.data.FWRegulator
        return agroproto.data.FWRegulator.FWRegulatorT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == Data().Warning:
        import agroproto.data.Warning
        return agroproto.data.Warning.WarningT.InitFromBuf(table.Bytes, table.Pos)
    return None
