# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Edge(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Edge()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEdge(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Edge
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Edge
    def Coords(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from agroproto.common.Point import Point
            obj = Point()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Edge
    def CoordsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Edge
    def CoordsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # Edge
    def IsTarget(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Edge
    def IsTracked(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def Start(builder): builder.StartObject(3)
def EdgeStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCoords(builder, coords): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(coords), 0)
def EdgeAddCoords(builder, coords):
    """This method is deprecated. Please switch to AddCoords."""
    return AddCoords(builder, coords)
def StartCoordsVector(builder, numElems): return builder.StartVector(8, numElems, 4)
def EdgeStartCoordsVector(builder, numElems):
    """This method is deprecated. Please switch to Start."""
    return StartCoordsVector(builder, numElems)
def AddIsTarget(builder, isTarget): builder.PrependBoolSlot(1, isTarget, 0)
def EdgeAddIsTarget(builder, isTarget):
    """This method is deprecated. Please switch to AddIsTarget."""
    return AddIsTarget(builder, isTarget)
def AddIsTracked(builder, isTracked): builder.PrependBoolSlot(2, isTracked, 0)
def EdgeAddIsTracked(builder, isTracked):
    """This method is deprecated. Please switch to AddIsTracked."""
    return AddIsTracked(builder, isTracked)
def End(builder): return builder.EndObject()
def EdgeEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)
import agroproto.common.Point
try:
    from typing import List
except:
    pass

class EdgeT(object):

    # EdgeT
    def __init__(self):
        self.coords = None  # type: List[agroproto.common.Point.PointT]
        self.isTarget = False  # type: bool
        self.isTracked = False  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        edge = Edge()
        edge.Init(buf, pos)
        return cls.InitFromObj(edge)

    @classmethod
    def InitFromObj(cls, edge):
        x = EdgeT()
        x._UnPack(edge)
        return x

    # EdgeT
    def _UnPack(self, edge):
        if edge is None:
            return
        if not edge.CoordsIsNone():
            self.coords = []
            for i in range(edge.CoordsLength()):
                if edge.Coords(i) is None:
                    self.coords.append(None)
                else:
                    point_ = agroproto.common.Point.PointT.InitFromObj(edge.Coords(i))
                    self.coords.append(point_)
        self.isTarget = edge.IsTarget()
        self.isTracked = edge.IsTracked()

    # EdgeT
    def Pack(self, builder):
        if self.coords is not None:
            StartCoordsVector(builder, len(self.coords))
            for i in reversed(range(len(self.coords))):
                self.coords[i].Pack(builder)
            coords = builder.EndVector()
        Start(builder)
        if self.coords is not None:
            AddCoords(builder, coords)
        AddIsTarget(builder, self.isTarget)
        AddIsTracked(builder, self.isTracked)
        edge = End(builder)
        return edge
