# automatically generated by the FlatBuffers compiler, do not modify

# namespace: data

class WarningType(object):
    LowFreq = 0
    DirtyCamera = 1
    CameraCalib = 2
    SteeringCalib = 3
    HighCTE = 4

